import catalogJson from './astraCatalog.json';

export type AstraIconName = keyof typeof catalogJson;

export const ASTRA_ICON_SRC: Record<string, string> = catalogJson;

export const ASTRA_ICON_ALIASES: Record<string, AstraIconName> = {
  ai: 'bulb',
  alert: 'info',
  alertCircle: 'info',
  anchor: 'flag',
  arrowRight: 'call_in',
  bag: 'shopping_bag',
  brain: 'gears',
  building: 'bank',
  building2: 'bank',
  calendar: 'calendar',
  camera: 'camera',
  card: 'card',
  cart: 'cart',
  chart: 'chart_line',
  chat: 'chat',
  check: 'cart_ok',
  checkCircle: 'thumbs_up',
  chevron: 'cursor',
  circle: 'disc',
  clapperboard: 'film',
  clock: 'clock',
  copyright: 'document',
  cpu: 'gears',
  create: 'edit',
  credits: 'signal',
  crown: 'award',
  currency: 'abacus',
  dashboard: 'monitor',
  document: 'document',
  dollarSign: 'money_bag',
  download: 'download',
  edit: 'edit',
  error: 'cart_remove',
  euro: 'thought_money',
  eye: 'glasses',
  file: 'document',
  flag: 'flag',
  flask: 'bulb',
  flaskConical: 'bulb',
  folder: 'folder',
  form: 'form',
  gallery: 'film',
  gem: 'award',
  generate: 'spotlight',
  gift: 'award',
  globe: 'globe',
  hand: 'thumbs_up',
  headphones: 'headphones',
  headset: 'headset',
  heart: 'heart',
  home: 'home',
  identity: 'passport',
  image: 'camera',
  imageIcon: 'camera',
  info: 'info',
  layoutDashboard: 'monitor',
  link2: 'sync',
  loader: 'sync',
  lock: 'lock',
  logIn: 'user',
  logOut: 'executive',
  login: 'user',
  logout: 'executive',
  mail: 'mail',
  mailOpen: 'mail_open',
  menu: 'org',
  metrics: 'chart_bar',
  mic: 'mic',
  money: 'money_bag',
  org: 'org',
  palette: 'mixer',
  passport: 'passport',
  percent: 'percent',
  phone: 'phone',
  premium: 'award',
  refresh: 'refresh',
  refreshCw: 'refresh',
  search: 'search',
  security: 'vault',
  settings: 'gears',
  shield: 'vault',
  sliders: 'sliders',
  sparkles: 'spotlight',
  star: 'star',
  success: 'thumbs_up',
  sun: 'spotlight',
  support: 'support',
  sync: 'sync',
  trash: 'trash',
  upload: 'upload',
  user: 'user',
  userPlus: 'executive',
  users: 'users',
  vault: 'vault',
  video: 'video',
  wand: 'edit',
  wand2: 'edit',
  watch: 'clock',
  x: 'cart_remove',
  zap: 'power',
};

export type AstraAlias = keyof typeof ASTRA_ICON_ALIASES;

export function resolveAstraIcon(name: string): AstraIconName {
  if (name in ASTRA_ICON_SRC) return name as AstraIconName;
  const mapped = ASTRA_ICON_ALIASES[name];
  if (mapped) return mapped;
  return 'star';
}

export function astraIconSrc(name: string): string {
  const key = resolveAstraIcon(name);
  return ASTRA_ICON_SRC[key] ?? `/icons/astra/${key}.png`;
}
